config/routes.rb
Rails.application.routes.draw do
  resources :distributions
  resources :lots
  resources :items
  resources :item_types
  resources :coordinators
  resources :politics
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/politic.rb
class Politic < ApplicationRecord
end

app/controllers/politics_controller.rb
class PoliticsController < ApplicationController
  before_action :set_politic, only: [:show, :edit, :update, :destroy]

  # GET /politics
  # GET /politics.json
  def index
    @politics = Politic.all
  end

  # GET /politics/1
  # GET /politics/1.json
  def show
  end

  # GET /politics/new
  def new
    @politic = Politic.new
  end

  # GET /politics/1/edit
  def edit
  end

  # POST /politics
  # POST /politics.json
  def create
    @politic = Politic.new(politic_params)

    respond_to do |format|
      if @politic.save
        format.html { redirect_to @politic, notice: 'Politic was successfully created.' }
        format.json { render :show, status: :created, location: @politic }
      else
        format.html { render :new }
        format.json { render json: @politic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /politics/1
  # PATCH/PUT /politics/1.json
  def update
    respond_to do |format|
      if @politic.update(politic_params)
        format.html { redirect_to @politic, notice: 'Politic was successfully updated.' }
        format.json { render :show, status: :ok, location: @politic }
      else
        format.html { render :edit }
        format.json { render json: @politic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /politics/1
  # DELETE /politics/1.json
  def destroy
    @politic.destroy
    respond_to do |format|
      format.html { redirect_to politics_url, notice: 'Politic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_politic
      @politic = Politic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def politic_params
      params.require(:politic).permit(:name, :phone, :political_party, :legend)
    end
end

app/helpers/politics_helper.rb
module PoliticsHelper
end

app/views/politics/_form.html.erb
<%= form_with(model: politic, local: true) do |form| %>
  <% if politic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(politic.errors.count, "error") %> prohibited this politic from being saved:</h2>

      <ul>
      <% politic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :political_party %>
    <%= form.text_field :political_party %>
  </div>

  <div class="field">
    <%= form.label :legend %>
    <%= form.text_field :legend %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/politics/edit.html.erb
<h1>Editing Politic</h1>

<%= render 'form', politic: @politic %>

<%= link_to 'Show', @politic %> |
<%= link_to 'Back', politics_path %>

app/views/politics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Politics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Political party</th>
      <th>Legend</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @politics.each do |politic| %>
      <tr>
        <td><%= politic.name %></td>
        <td><%= politic.phone %></td>
        <td><%= politic.political_party %></td>
        <td><%= politic.legend %></td>
        <td><%= link_to 'Show', politic %></td>
        <td><%= link_to 'Edit', edit_politic_path(politic) %></td>
        <td><%= link_to 'Destroy', politic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Politic', new_politic_path %>

app/views/politics/new.html.erb
<h1>New Politic</h1>

<%= render 'form', politic: @politic %>

<%= link_to 'Back', politics_path %>

app/views/politics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @politic.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @politic.phone %>
</p>

<p>
  <strong>Political party:</strong>
  <%= @politic.political_party %>
</p>

<p>
  <strong>Legend:</strong>
  <%= @politic.legend %>
</p>

<%= link_to 'Edit', edit_politic_path(@politic) %> |
<%= link_to 'Back', politics_path %>