config/routes.rb
Rails.application.routes.draw do
  resources :distributions
  resources :lots
  resources :items
  resources :item_types
  resources :coordinators
  resources :politics
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/distribution.rb
class Distribution < ApplicationRecord
  has_many :item
  belongs_to :coordinator
  belongs_to :lot
end

app/controllers/distributions_controller.rb
# frozen_string_literal: true
class DistributionsController < ApplicationController
  before_action :set_distribution, only: %i[show edit update destroy]

  # GET /distributions
  # GET /distributions.json
  def index
    @distributions = Distribution.all
  end

  # GET /distributions/1
  # GET /distributions/1.json
  def show; end

  # GET /distributions/new
  def new
    @distribution = Distribution.new
  end

  # GET /distributions/1/edit
  def edit; end

  # POST /distributions
  # POST /distributions.json
  def create
    @distribution = Distribution.new(distribution_params)

    respond_to do |format|
      if @distribution.save
        format.html { redirect_to @distribution, notice: 'Distribution was successfully created.' }
        format.json { render :show, status: :created, location: @distribution }
      else
        format.html { render :new }
        format.json { render json: @distribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /distributions/1
  # PATCH/PUT /distributions/1.json
  def update
    respond_to do |format|
      if @distribution.update(distribution_params)
        format.html { redirect_to @distribution, notice: 'Distribution was successfully updated.' }
        format.json { render :show, status: :ok, location: @distribution }
      else
        format.html { render :edit }
        format.json { render json: @distribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /distributions/1
  # DELETE /distributions/1.json
  def destroy
    @distribution.destroy
    respond_to do |format|
      format.html { redirect_to distributions_url, notice: 'Distribution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_distribution
    @distribution = Distribution.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def distribution_params
    params.require(:distribution).permit(:item_id, :quantity, :coordinator_id, :lot_id)
  end
end

app/helpers/distributions_helper.rb
module DistributionsHelper
end

app/views/distributions/_form.html.erb
<%= form_with(model: distribution, local: true) do |form| %>
  <% if distribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(distribution.errors.count, "error") %> prohibited this distribution from being saved:</h2>

      <ul>
      <% distribution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.text_field :item_id %>
  </div>

  <div class="field">
    <%= form.label :coordinator_id %>
    <%= form.text_field :coordinator_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/distributions/edit.html.erb
<h1>Editing Distribution</h1>

<%= render 'form', distribution: @distribution %>

<%= link_to 'Show', @distribution %> |
<%= link_to 'Back', distributions_path %>

app/views/distributions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Distributions</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Coordinator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @distributions.each do |distribution| %>
      <tr>
        <td><%= distribution.item %></td>
        <td><%= distribution.coordinator %></td>
        <td><%= link_to 'Show', distribution %></td>
        <td><%= link_to 'Edit', edit_distribution_path(distribution) %></td>
        <td><%= link_to 'Destroy', distribution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Distribution', new_distribution_path %>

app/views/distributions/new.html.erb
<h1>New Distribution</h1>

<%= render 'form', distribution: @distribution %>

<%= link_to 'Back', distributions_path %>

app/views/distributions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @distribution.item %>
</p>

<p>
  <strong>Coordinator:</strong>
  <%= @distribution.coordinator %>
</p>

<%= link_to 'Edit', edit_distribution_path(@distribution) %> |
<%= link_to 'Back', distributions_path %>