config/routes.rb
Rails.application.routes.draw do
  resources :distributions
  resources :lots
  resources :items
  resources :item_types
  resources :coordinators
  resources :politics
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lot.rb
class Lot < ApplicationRecord
  belongs_to :item
end

app/controllers/lots_controller.rb
# frozen_string_literal: true
class LotsController < ApplicationController
  before_action :set_lot, only: %i[show edit update destroy]

  # GET /lots
  # GET /lots.json
  def index
    @lots = Lot.all
  end

  # GET /lots/1
  # GET /lots/1.json
  def show; end

  # GET /lots/new
  def new
    @lot = Lot.new
  end

  # GET /lots/1/edit
  def edit; end

  # POST /lots
  # POST /lots.json
  def create
    @lot = Lot.new(lot_params)

    respond_to do |format|
      if @lot.save
        format.html { redirect_to @lot, notice: 'Lot was successfully created.' }
        format.json { render :show, status: :created, location: @lot }
      else
        format.html { render :new }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lots/1
  # PATCH/PUT /lots/1.json
  def update
    respond_to do |format|
      if @lot.update(lot_params)
        format.html { redirect_to @lot, notice: 'Lot was successfully updated.' }
        format.json { render :show, status: :ok, location: @lot }
      else
        format.html { render :edit }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lots/1
  # DELETE /lots/1.json
  def destroy
    @lot.destroy
    respond_to do |format|
      format.html { redirect_to lots_url, notice: 'Lot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lot
    @lot = Lot.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def lot_params
    params.require(:lot).permit(:item_id, :politic_id, :origin, :initial_quantity, :current_quantity)
  end
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/views/lots/_form.html.erb
<%= form_with(model: lot, local: true) do |form| %>
  <% if lot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lot.errors.count, "error") %> prohibited this lot from being saved:</h2>

      <ul>
      <% lot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.text_field :item_id %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin %>
  </div>

  <div class="field">
    <%= form.label :initial_quantity %>
    <%= form.number_field :initial_quantity %>
  </div>

  <div class="field">
    <%= form.label :current_quantity %>
    <%= form.number_field :current_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lots/edit.html.erb
<h1>Editing Lot</h1>

<%= render 'form', lot: @lot %>

<%= link_to 'Show', @lot %> |
<%= link_to 'Back', lots_path %>

app/views/lots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lots</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Origin</th>
      <th>Initial quantity</th>
      <th>Current quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lots.each do |lot| %>
      <tr>
        <td><%= lot.item %></td>
        <td><%= lot.origin %></td>
        <td><%= lot.initial_quantity %></td>
        <td><%= lot.current_quantity %></td>
        <td><%= link_to 'Show', lot %></td>
        <td><%= link_to 'Edit', edit_lot_path(lot) %></td>
        <td><%= link_to 'Destroy', lot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lot', new_lot_path %>

app/views/lots/new.html.erb
<h1>New Lot</h1>

<%= render 'form', lot: @lot %>

<%= link_to 'Back', lots_path %>

app/views/lots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @lot.item %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @lot.origin %>
</p>

<p>
  <strong>Initial quantity:</strong>
  <%= @lot.initial_quantity %>
</p>

<p>
  <strong>Current quantity:</strong>
  <%= @lot.current_quantity %>
</p>

<%= link_to 'Edit', edit_lot_path(@lot) %> |
<%= link_to 'Back', lots_path %>